package ventanas;

import Sockets.Replicador;
import franquiciaapp.XMLSucursal;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 * Clase que permite introducir elegir el coordinador y su .
 *
 * @author daniel
 */
public class InfoCoordinador extends javax.swing.JFrame {

    private GestionSucursal padre = null;

    public InfoCoordinador() {
        initComponents();
        //XMLProducto xml = new XMLProducto();
    }

    public InfoCoordinador(GestionSucursal padre) {
        this.padre = padre;
        initComponents();
        inicializar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jLImagen = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTIP = new javax.swing.JTextField();
        jTPuerto = new javax.swing.JTextField();
        jCBNodo = new javax.swing.JComboBox();
        jBAceptar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrinho supermercado.png"))); // NOI18N
        jLabel3.setText("Logo");
        jLabel3.setBounds(320, 50, 90, 100);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLNombre.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLNombre.setText("IP Server:");
        jLNombre.setBounds(150, 160, 70, 20);
        jLayeredPane1.add(jLNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLDescripcion.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLDescripcion.setText("Puerto:");
        jLDescripcion.setBounds(150, 200, 70, 20);
        jLayeredPane1.add(jLDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLImagen.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLImagen.setText("Nodo Coordinador:");
        jLImagen.setBounds(150, 240, 130, 18);
        jLayeredPane1.add(jLImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("SuperMercados XYZ");
        jLabel1.setBounds(130, 100, 200, 30);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIPActionPerformed(evt);
            }
        });
        jTIP.setBounds(240, 150, 250, 30);
        jLayeredPane1.add(jTIP, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTPuertoActionPerformed(evt);
            }
        });
        jTPuerto.setBounds(240, 190, 250, 30);
        jLayeredPane1.add(jTPuerto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCBNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNodoActionPerformed(evt);
            }
        });
        jCBNodo.setBounds(300, 240, 190, 20);
        jLayeredPane1.add(jCBNodo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBAceptar.setText("Aceptar");
        jBAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAceptarActionPerformed(evt);
            }
        });
        jBAceptar.setBounds(200, 300, 110, 30);
        jLayeredPane1.add(jBAceptar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jBCancelar.setBounds(330, 300, 110, 30);
        jLayeredPane1.add(jBCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos-verdes.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBounds(0, 0, 620, 400);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIPActionPerformed

    private void jBAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAceptarActionPerformed
        if ((this.jTIP.getText().equals("")) || (this.jTPuerto.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Algun campo esta VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            InfoCoordinador Registro = new InfoCoordinador();
            Registro.setVisible(true);

        } else {
            XMLSucursal sucursal = new XMLSucursal();
            boolean flag = sucursal.registrarCoordinador(this.jTIP.getText(),
                    this.jTPuerto.getText(), this.jCBNodo.getSelectedItem().toString());
            if (flag = false) {
                JOptionPane.showMessageDialog(null, "No se pudo registrar el coordinador", "ERROR", JOptionPane.ERROR_MESSAGE);
                InfoCoordinador Registro = new InfoCoordinador();
                Registro.setVisible(true);
                this.dispose();
            } else {
                this.padre.dispose();
                GestionProducto Gestion = new GestionProducto();
                Gestion.setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(null, "Se ha registrado el nodo coordinador", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);

                //Replicar
                Replicador replicador = new Replicador("nodoCoordinador.xml");
                new Thread(replicador).start();
            }
        }
    }//GEN-LAST:event_jBAceptarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBNodoActionPerformed

    private void jTPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPuertoActionPerformed
    }//GEN-LAST:event_jTPuertoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoCoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoCoordinador().setVisible(true);
            }
        });
    }

    private void inicializar() {
        ArrayList<String> sucursales = this.padre.getSucursales();
        Iterator i = sucursales.iterator();
        while (i.hasNext()) {
            this.jCBNodo.addItem(i.next().toString());
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAceptar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox jCBNodo;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLImagen;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTIP;
    private javax.swing.JTextField jTPuerto;
    // End of variables declaration//GEN-END:variables
}
