/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package franquiciaapp;

import Sockets.Replicador;
import javax.swing.JOptionPane;
import ventanas.ActualizarProducto;
import ventanas.GestionInventario;

/**
 *
 * @author Diego Alienware
 */
public class ActualizarInventario extends javax.swing.JFrame {

    /**
     * Creates new form ActualizarInventario
     */
    public ActualizarInventario() {
        initComponents();
    }
    private String vacio = null;
    private String producto = "";
    private GestionInventario padre = null;
    
    public ActualizarInventario(GestionInventario padre) {
        this.padre = padre;
        initComponents();
        //XMLProducto xml = new XMLProducto();
        inicializar();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jLCosto = new javax.swing.JLabel();
        jLCantidad = new javax.swing.JLabel();
        jLStatus = new javax.swing.JLabel();
        jCBStatus = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTDescripcion = new javax.swing.JTextField();
        jTCantidad = new javax.swing.JTextField();
        jBActualizar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jTCosto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrinho supermercado.png"))); // NOI18N
        jLabel3.setText("Logo");
        jLabel3.setBounds(320, 50, 90, 100);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLNombre.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLNombre.setText("Nombre:");
        jLNombre.setBounds(100, 160, 60, 20);
        jLayeredPane1.add(jLNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLDescripcion.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLDescripcion.setText("Descripcion:");
        jLDescripcion.setBounds(100, 200, 90, 20);
        jLayeredPane1.add(jLDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLCosto.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLCosto.setText("Costo: ");
        jLCosto.setBounds(100, 240, 60, 18);
        jLayeredPane1.add(jLCosto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLCantidad.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLCantidad.setText("Cantidad:");
        jLCantidad.setBounds(100, 280, 80, 18);
        jLayeredPane1.add(jLCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLStatus.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLStatus.setText("Estatus:");
        jLStatus.setBounds(100, 320, 50, 18);
        jLayeredPane1.add(jLStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCBStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Activo", "Inactivo" }));
        jCBStatus.setBounds(200, 320, 90, 20);
        jLayeredPane1.add(jCBStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("SuperMercados XYZ");
        jLabel1.setBounds(130, 100, 200, 30);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreActionPerformed(evt);
            }
        });
        jTNombre.setBounds(200, 150, 250, 30);
        jLayeredPane1.add(jTNombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTDescripcion.setBounds(200, 190, 250, 30);
        jLayeredPane1.add(jTDescripcion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCantidadActionPerformed(evt);
            }
        });
        jTCantidad.setBounds(200, 270, 250, 30);
        jLayeredPane1.add(jTCantidad, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBActualizar.setText("Actualizar");
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });
        jBActualizar.setBounds(140, 360, 97, 23);
        jLayeredPane1.add(jBActualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jBCancelar.setBounds(280, 360, 97, 23);
        jLayeredPane1.add(jBCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCostoActionPerformed(evt);
            }
        });
        jTCosto.setBounds(200, 230, 250, 30);
        jLayeredPane1.add(jTCosto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreActionPerformed

    private void jTCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCantidadActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        // TODO add your handling code here:
        if ((this.jTNombre.getText().equals("")) || (this.jTDescripcion.getText().equals("")) || (this.jTCantidad.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "Algun campo esta VACIO", "ERROR", JOptionPane.ERROR_MESSAGE);
            ActualizarProducto Registro = new ActualizarProducto();
            Registro.setVisible(true);

        } else {
            XMLInventario inventarios = new XMLInventario();
            boolean flag = inventarios.actualizarInventario(this.producto, this.jTNombre.getText(),
                this.jTDescripcion.getText(), this.jTCosto.getText(),
                this.jTCantidad.getText());
            if (flag = false) {
                JOptionPane.showMessageDialog(null, "No se pudo crear usuario", "ERROR", JOptionPane.ERROR_MESSAGE);
                ActualizarInventario Registro = new ActualizarInventario();
                Registro.setVisible(true);
                this.dispose();
            } else {
                this.padre.dispose();
                GestionInventario Inventario = new GestionInventario();
                Inventario.setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(null, "Producto modificado correctamente", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("LLEGANDO");
                //replica el archivo de productos para actualizar
                Replicador replicador = new Replicador("inventarioProductos.xml");
                new Thread(replicador).start();
            }

        }
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCostoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarInventario().setVisible(true);
            }
        });
    }
    
    private void inicializar() {

        Inventario productoSelec = this.padre.getProductoInventarioSeleccionado();
        this.producto = productoSelec.getNombre();
        jTNombre.setText(productoSelec.getNombre());
        jTDescripcion.setText(productoSelec.getDescripcion());
        jTCosto.setText(productoSelec.getCosto());
        jTCantidad.setText(productoSelec.getCantidad());
        //jTImagen.setText(productoSelec.getFoto());        
        //jCBStatus.setSelectedItem(productoSelec.getStatus());

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JComboBox jCBStatus;
    private javax.swing.JLabel jLCantidad;
    private javax.swing.JLabel jLCosto;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTCantidad;
    private javax.swing.JTextField jTCosto;
    private javax.swing.JTextField jTDescripcion;
    private javax.swing.JTextField jTNombre;
    // End of variables declaration//GEN-END:variables
}
