/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package franquiciaapp;

import java.io.File;
import javax.swing.table.DefaultTableModel;

/**
 *Clase que permite la visualizacion y eliminacion
 * de los productos
 * @author gracielalucena
 */
public class GestionProducto extends javax.swing.JFrame {

    /**
     * Creates new form GestionProducto
     */
    int selected = -1;
    private String archivo = "listaProductos.xml";
    private String producto;

    
    public GestionProducto() {
        initComponents();
        
        XMLProducto xml = new XMLProducto();
        xml.listarProductos(this, archivo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        gestor = new javax.swing.JTable();
        eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setLocation(new java.awt.Point(0, 0));

        gestor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Descripcion", "Foto", "Costo"
            }
        ));
        jScrollPane1.setViewportView(gestor);

        jScrollPane1.setBounds(50, 100, 490, 150);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        eliminar.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/franquiciaapp/delete.png"))); // NOI18N
        eliminar.setText("Eliminar.");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        eliminar.setBounds(400, 270, 140, 60);
        jLayeredPane1.add(eliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/franquiciaapp/carrinho supermercado.png"))); // NOI18N
        jLabel1.setBounds(210, 0, 90, 100);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("SuperMercados XYZ");
        jLabel2.setBounds(50, 60, 184, 22);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/franquiciaapp/fondos-verdes.jpg"))); // NOI18N
        jLabel3.setBounds(-5, 0, 600, 370);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLayeredPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Permite eliminar los productos, que seleccione en la lista
     * dinamica
     * @param evt 
     */
    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        // TODO add your handling code here:
        System.out.print("estoy aqui");
                System.out.print(selected);

        selected = gestor.getSelectedRow();
        
                System.out.print(gestor.getSelectedRow());
         if (selected >= 0) {
            String nombrearchivo = (String) gestor.getValueAt(selected, 0);
            System.out.print(nombrearchivo);
               //File archivo = new File(this.carpetausuario + "/" + nombrearchivo);
            
           // XMLnodos xmlnodo = new XMLnodos();
            //int var=0;
            //for (int i = 0; i < xmlnodo.cantNodos(); i++) {
             
              //  var=xmlnodo.cargaArchivos(i);
               // HiloReplicador hiloReplicador;
                // OJO EL 1200 ES EL PUERTO DE ENVIAR, EL DE ESCUCHA SE ESTA USANDO POR ARGUMENTO
              //if(var==1){
               // hiloReplicador = new HiloReplicador(Datos.getIp_vecino(), Datos.getPuerto_entrada(),Datos.getPuerto_salida(),archivo, this.carpetausuario,"eliminar");
                // hiloReplicador.start();
              //}
               XMLProducto xml = new XMLProducto();
               xml.borrarProducto(archivo,nombrearchivo);
              //archivo.delete();

        // TODO add your handling code here:
        // }
                            ((DefaultTableModel) this.gestor.getModel()).removeRow(selected);

         }
         else
             System.out.print("AHORA ACA");
                         System.out.print(selected);

    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionProducto().setVisible(true);
            }
        });
    }
    
    /**
     * Carga la tabla con los productos disponibles
     * @param nombre
     * @param descripcion
     * @param foto
     * @param costo 
     */
     public void agregarfila(String nombre, String descripcion, String foto, String costo) {
        ((DefaultTableModel) this.gestor.getModel()).addRow(new Object[]{nombre, descripcion, foto, costo});
    
    }
     
      public int getRowCount() {
        return gestor.getRowCount();
    }
     
     private void gestorMouseClicked(java.awt.event.MouseEvent evt) {                                    

              this.selected = gestor.getSelectedRow();
                              System.out.print(selected);

 
             // TODO add your handling code here:
        // TODO add your handling code here:
    }              
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminar;
    private javax.swing.JTable gestor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
