/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package franquiciaapp;
import java.awt.*;
import javax.swing.*;


/**
 *
 * @author gracielalucena
 */
public class PanelImagen extends javax.swing.JPanel {

    String imagen1;
    /**
     * Creates new form PanelImagen
     */
    public PanelImagen(String imagen) {
        initComponents();
        imagen1 = imagen; 
        this.setSize(150, 150);
    }
    
    public void paint (Graphics g){
        Dimension tam = getSize();
        ImageIcon fondo = new ImageIcon(new ImageIcon(getClass().getResource("/imagenes/"+imagen1)).getImage());
        g.drawImage(fondo.getImage(), 0,0, tam.width , tam.width, null);
        setOpaque(false);
        super.paintComponents(g);
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
